name: Build

on:
  push:
    branches:
      - "*"
      - "!master"
      - "!release/v*"

env:
  NODE_VERSION: 14.x

jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          scope: ${{ github.repository_owner }}

      - name: Init
        run: yarn --no-lockfile

      - name: Build
        run: yarn run build -- -- --prod
