name: Build

on:
  push:
    branches:
    - "*"
    - "!master"
    - "!release/v*"

jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Init
        run: yarn

      - name: Build
        run: yarn run build:libs -- --prod
