name: Check Release

on:
  pull_request:
    branches:
      - "release/v*"
#    tags:
#      - v*.*.*
#      - v*.*.*-*.*

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Init
        run: yarn

      #- name: Version
      #  run: lerna version


      - name: Build
        run: yarn run build:libs -- --prod

     # - name: Publish
     #  run: lerna publish from-git --contents dist --no-git-tag-version --no-commit-hooks --no-push --force-publish --yes --graph-type all
