name: Build

on:
  push:
    branches:
    - "release/v*"


jobs:
  check_release_build:
    runs-on: ubuntu-latest
    if: github.
    steps:
      - uses: actions/checkout@v2

      - name: Init
        run: yarn

    #  - name: Version
    #    run: lerna version

      - name: Build
        run: yarn run build:libs -- --prod
      # - name: Publish
      #  run: lerna publish from-git --contents dist --no-git-tag-version --no-commit-hooks --no-push --force-publish --yes --graph-type all
