name: Check Release Version

on:
  pull_request:
    branches:
      - "release/v*"

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - id: branch_version
        uses: battila7/get-version-action@v2

      - name: Echo
        run: echo ${{package-version.outputs.current-version}}
