name: Check Release Version

on:
  pull_request:
    branches:
      - "release/v*"

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name:  package_version_str
        id: package_version_str
        uses: martinbeentjes/npm-get-version-action@master


      - id: branch_version
        name: branch_version
        uses: battila7/get-version-action@v2

      - name: Parse Ref Version
        id: refVersion
        uses: doptools/action-parse-semver@main
        with:
          version: "${{ github.ref }}"
          versionRegex: '\/v(.*)$'

      - name: Parse Package Version
        id: pkgVersion
        uses: doptools/action-parse-semver@main
        with:
          version: "${{ steps.package_version.outputs.current-version }}"
          versionRegex: '\/v(.*)$'

      - name: Echo
        run: |
          echo ${{steps.package_version.outputs.current-version}}
          echo ${{steps.branch_version.outputs.version-without-v}}

          echo ${{steps.refVersion.outputs.full}}
          echo ${{steps.pkgVersion.outputs.full}}
