name: Publish

on:
  release:
    types: [published]

env:
  NODE_VERSION: 14.x
  PACKAGE_ACCESS: public # public | restricted

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          scope: ${{ github.owner }}

      - name: Parse branch version
        id: refVersion
        uses: doptools/action-parse-semver@main
        with:
          version: "${{ github.ref }}"
          versionRegex: '\/v(.*)$'

      - name: Init
        run: |
          echo ${{ github.ref }}
          yarn

      - name: Set versions
        run: |
          npx lerna version ${{steps.refVersion.outputs.full}} --force-publish --no-commit-hooks --no-git-tag-version --no-push --yes
          git commit -a -m versions

      - name: Build
        run: yarn run build:libs -- --prod

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        run: lerna publish --no-git-tag-version --no-commit-hooks --no-push --force-publish --yes --graph-type all ${{steps.refVersion.outputs.full}}
