name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: fregante/setup-git-user@v1


      - name: Parse branch version
        id: refVersion
        uses: doptools/action-parse-semver@main
        with:
          version: "${{ github.ref }}"
          versionRegex: '\/v(.*)$'

      - name: Init
        run: |
          echo ${{ github.ref }}
          yarn

      - name: Set versions
        run: npx lerna version ${{steps.refVersion.outputs.full}} --force-publish --no-commit-hooks --no-git-tag-version --no-push --yes

      - name: Build
        run: yarn run build:libs -- --prod

      - name: Publish
        run: lerna publish from-package --contents dist --no-git-tag-version --no-commit-hooks --no-push --force-publish --yes --graph-type all

# --contents dist --no-git-tag-version --no-commit-hooks --no-push --force-publish --yes --graph-type all
