name: Publish

on:
  push:
    branches:
      - "release/v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1

      - name: Get package version
        id: package_version_str
        uses: martinbeentjes/npm-get-version-action@master

      - name: Parse package version
        id: pkgVersion
        uses: doptools/action-parse-semver@main
        with:
          version: "${{ steps.package_version_str.outputs.current-version }}"
          versionRegex: "(.*)"

      - name: Init
        run: |
          echo ${{ github.ref }}
          yarn

      - name: Set versions
        run: npx lerna version ${{steps.pkgVersion.outputs.full}} --force-publish --no-commit-hooks --no-push --yes

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.pkgVersion.outputs.full }}
          name: Version ${{ steps.pkgVersion.outputs.full }}
          commit: ${{ github.ref }}
          body: |
            Generated Release ${{ steps.pkgVersion.outputs.full }}
          draft: true
          prerelease: ${{ steps.version.outputs.isPrerelease }}
          token: ${{ github.token }}

# --contents dist --no-git-tag-version --no-commit-hooks --no-push --force-publish --yes --graph-type all
